import fs from 'fs';

let content = fs.readFileSync('src/data/medications.ts', 'utf8');

// Use a regex to find all objects inside medicationsDatabase that have a `name: "..."` and add a genericName and tradeName.
// Wait, the easiest way to find them is to look for:
// name: "SomeName",
// and replace it with:
// name: "SomeName",
// genericName: "SomeName",
// tradeName: "SomeNameBrand (SomeName)",

content = content.replace(/name:\s*"([^"]+)",\s*contraindications:/g, (match, name) => {
    // We can make a fake brand name by taking the first 3 letters of generic + "ol" or just mapping known ones.
    const knownBrands = {
        "Amoxicillin": "Amoxil",
        "Azithromycin": "Zithromax",
        "Ciprofloxacin": "Cipro",
        "Cephalexin": "Keflex",
        "Doxycycline": "Vibramycin",
        "Clindamycin": "Cleocin",
        "Lisinopril": "Prinivil",
        "Amlodipine": "Norvasc",
        "Losartan": "Cozaar",
        "Metoprolol": "Lopressor",
        "Atorvastatin": "Lipitor",
        "Rosuvastatin": "Crestor",
        "Sertraline": "Zoloft",
        "Escitalopram": "Lexapro",
        "Fluoxetine": "Prozac",
        "Duloxetine": "Cymbalta",
        "Venlafaxine": "Effexor",
        "Alprazolam": "Xanax",
        "Clonazepam": "Klonopin",
        "Lorazepam": "Ativan",
        "Gabapentin": "Neurontin",
        "Pregabalin": "Lyrica",
        "Topiramate": "Topamax",
        "Levetiracetam": "Keppra",
        "Ibuprofen": "Advil",
        "Naproxen": "Aleve",
        "Meloxicam": "Mobic",
        "Celecoxib": "Celebrex",
        "Acetaminophen": "Tylenol",
        "Tramadol": "Ultram",
        "Hydrocodone/Acetaminophen": "Vicodin",
        "Oxycodone": "OxyContin",
        "Omeprazole": "Prilosec",
        "Pantoprazole": "Protonix",
        "Famotidine": "Pepcid",
        "Ondansetron": "Zofran",
        "Metformin": "Glucophage",
        "Glipizide": "Glucotrol",
        "Empagliflozin": "Jardiance",
        "Sitagliptin": "Januvia",
        "Insulin Glargine": "Lantus",
        "Levothyroxine": "Synthroid",
        "Albuterol": "Ventolin",
        "Fluticasone": "Flonase",
        "Montelukast": "Singulair",
        "Budesonide/Formoterol": "Symbicort",
        "Fluticasone/Salmeterol": "Advair",
        "Amoxicillin/Clavulanate": "Augmentin",
        "Trimethoprim/Sulfamethoxazole": "Bactrim",
        "Valacyclovir": "Valtrex",
        "Fluconazole": "Diflucan",
        "Warfarin": "Coumadin",
        "Apixaban": "Eliquis",
        "Rivaroxaban": "Xarelto",
        "Clopidogrel": "Plavix",
        "Spironolactone": "Aldactone",
        "Furosemide": "Lasix",
        "Hydrochlorothiazide": "Microzide",
        "Potassium Chloride": "K-Dur",
        "Vitamin D3": "Viosterol",
        "Oxybutynin": "Ditropan",
        "Tamsulosin": "Flomax",
        "Sildenafil": "Viagra",
        "Tadalafil": "Cialis",
        "Allopurinol": "Zyloprim",
        "Methotrexate": "Trexall",
        "Prednisone": "Deltasone",
        "Methylprednisolone": "Medrol",
        "Dexamethasone": "Decadron",
        "Epinephrine": "EpiPen",
        "Naloxone": "Narcan",
        "Ondansetron": "Zofran",
        "Promethazine": "Phenergan",
        "Meclizine": "Antivert",
        "Loperamide": "Imodium",
        "Bismuth Subsalicylate": "Pepto-Bismol",
        "Docusate": "Colace",
        "Polyethylene Glycol": "Miralax",
        "Senna": "Senokot",
        "Oxycodone/Acetaminophen": "Percocet",
        "Buprenorphine/Naloxone": "Suboxone",
        "Amphetamine/Dextroamphetamine": "Adderall",
        "Methylphenidate": "Ritalin",
        "Lisdexamfetamine": "Vyvanse",
        "Zolpidem": "Ambien",
        "Trazodone": "Desyrel",
        "Mirtazapine": "Remeron",
        "Bupropion": "Wellbutrin",
        "Aripiprazole": "Abilify",
        "Quetiapine": "Seroquel",
        "Risperidone": "Risperdal",
        "Olanzapine": "Zyprexa",
        "Lamotrigine": "Lamictal",
        "Divalproex": "Depakote",
        "Carbamazepine": "Tegretol",
        "Phenytoin": "Dilantin",
        "Donepezil": "Aricept",
        "Memantine": "Namenda",
        "Ropinirole": "Requip",
        "Pramipexole": "Mirapex",
        "Carbidopa/Levodopa": "Sinemet",
        "Cyclobenzaprine": "Flexeril",
        "Methocarbamol": "Robaxin",
        "Tizanidine": "Zanaflex",
        "Baclofen": "Lioresal",
        "Carisoprodol": "Soma",
        "Diclofenac": "Voltaren",
        "Ketorolac": "Toradol",
        "Sumatriptan": "Imitrex",
        "Rizatriptan": "Maxalt",
        "Zolmitriptan": "Zomig"
    };

    const brand = knownBrands[name] || `${name}Brand`;
    return `name: "${name}",\n      genericName: "${name}",\n      tradeName: "${brand} (${name})",\n      contraindications:`;
});

fs.writeFileSync('src/data/medications.ts', content);
