import fs from 'fs';

let content = fs.readFileSync('src/data/medications.ts', 'utf8');

const egyptianBrands = {
    "Amoxicillin": "Ibiamox",
    "Azithromycin": "Zithrokan",
    "Ciprofloxacin": "Ciprocin",
    "Cephalexin": "Keflex",
    "Doxycycline": "Vibramycin",
    "Clarithromycin": "Klacid",
    "Levofloxacin": "Tavanic",
    "Metronidazole": "Flagyl",
    "Nitrofurantoin": "Macrofuran",
    "Trimethoprim/Sulfamethoxazole": "Septrin",
    "Ibuprofen": "Brufen",
    "Acetaminophen": "Panadol",
    "Naproxen": "Proxen",
    "Celecoxib": "Celebrex",
    "Tramadol": "Tramal",
    "Diclofenac": "Voltaren",
    "Meloxicam": "Anti-cox",
    "Morphine": "Morphine",
    "Oxycodone": "OxyContin",
    "Gabapentin": "Gaptin",
    "Lisinopril": "Zestril",
    "Atorvastatin": "Ator",
    "Metoprolol": "Betaloc",
    "Losartan": "Amzaar",
    "Amlodipine": "Alkacap",
    "Enalapril": "Ezapril",
    "Valsartan": "Tareg",
    "Carvedilol": "Dilatrol",
    "Spironolactone": "Aldactone",
    "Warfarin": "Marevan",
    "Apixaban": "Eliquis",
    "Rivaroxaban": "Xarelto",
    "Clopidogrel": "Plavix",
    "Furosemide": "Lasix",
    "Hydrochlorothiazide": "Esidrex",
    "Sertraline": "Lustral",
    "Escitalopram": "Cipralex",
    "Fluoxetine": "Prozac",
    "Duloxetine": "Cymbalta",
    "Venlafaxine": "Effexor",
    "Alprazolam": "Xanax",
    "Clonazepam": "Amotril",
    "Lorazepam": "Ativan",
    "Pregabalin": "Lyrica",
    "Topiramate": "Topamax",
    "Levetiracetam": "Keppra",
    "Omeprazole": "Losec",
    "Pantoprazole": "Controloc",
    "Famotidine": "Antodine",
    "Ondansetron": "Danset",
    "Metformin": "Cidophage",
    "Glipizide": "Minidiab",
    "Empagliflozin": "Jardiance",
    "Sitagliptin": "Januvia",
    "Insulin Glargine": "Lantus",
    "Levothyroxine": "Eltroxin",
    "Albuterol": "Ventolin",
    "Fluticasone": "Flixonase",
    "Montelukast": "Singulair",
    "Budesonide/Formoterol": "Symbicort",
    "Amoxicillin/Clavulanate": "Augmentin",
    "Valacyclovir": "Valtrex",
    "Fluconazole": "Diflucan",
    "Potassium Chloride": "Potassium",
    "Vitamin D3": "Vidrop",
    "Oxybutynin": "Uripan",
    "Tamsulosin": "Omnic",
    "Sildenafil": "Virecta",
    "Tadalafil": "StarCop",
    "Allopurinol": "Zyloric",
    "Methotrexate": "Methotrexate",
    "Prednisone": "Hostacortin",
    "Methylprednisolone": "Solu-Medrol",
    "Dexamethasone": "Dexazone",
    "Epinephrine": "Epinephrine",
    "Naloxone": "Naloxone",
    "Promethazine": "Phenergan",
    "Meclizine": "Dizirest",
    "Loperamide": "Diax",
    "Bismuth Subsalicylate": "Pepto-Bismol",
    "Docusate": "Laxol",
    "Polyethylene Glycol": "LaxoPEG",
    "Senna": "Purgen",
    "Zolpidem": "Stilnox",
    "Trazodone": "Trittico",
    "Mirtazapine": "Remeron",
    "Bupropion": "Wellbutrin",
    "Aripiprazole": "Abilify",
    "Quetiapine": "Seroquel",
    "Risperidone": "Risperdal",
    "Olanzapine": "Zyprexa",
    "Lamotrigine": "Lamictal",
    "Divalproex": "Depakine",
    "Carbamazepine": "Tegretol",
    "Phenytoin": "Epanutin",
    "Donepezil": "Aricept",
    "Memantine": "Ebixa",
    "Ropinirole": "Requip",
    "Pramipexole": "Mirapex",
    "Carbidopa/Levodopa": "Sinemet",
    "Cyclobenzaprine": "Multi-Relax",
    "Methocarbamol": "Methocarbamol",
    "Tizanidine": "Sirdalud",
    "Baclofen": "Myofen",
    "Carisoprodol": "Soma",
    "Ketorolac": "Ketolac",
    "Sumatriptan": "Sumigran",
    "Rizatriptan": "Maxalt",
    "Zolmitriptan": "No-Migraine"
};

content = content.replace(/tradeName:\s*"([^"]+)"/g, (match, currentTradeName) => {
    // Extract generic name from between parentheses
    const matchObj = currentTradeName.match(/\(([^)]+)\)/);
    if (matchObj) {
        const genericName = matchObj[1];
        if (egyptianBrands[genericName]) {
            return `tradeName: "${egyptianBrands[genericName]} (${genericName})"`;
        }
    }
    return match;
});

fs.writeFileSync('src/data/medications.ts', content);
