import React, { useState, useEffect } from 'react';
import { Database, Trash2, RefreshCw, Search, FileText, BrainCircuit, Pill, MessageSquare, AlertCircle, CheckCircle, Download, Upload } from 'lucide-react';
import { db } from '../../lib/db';
import { cn } from '../../lib/utils';
import { toast } from 'sonner';
import { motion } from 'motion/react';

interface TableStats {
  name: string;
  count: number;
  label: string;
  icon: any;
  description: string;
  tableName: string;
}

export function DatabaseManagerSettings() {
  const [stats, setStats] = useState<TableStats[]>([]);
  const [loading, setLoading] = useState(true);
  const [clearing, setClearing] = useState<string | null>(null);

  const learnedTables = [
    { name: 'knowledge_encyclopedia', label: 'Medical Encyclopedia', icon: Search, description: 'Cached definitions and medical terms generated by AI.' },
    { name: 'knowledge_protocols', label: 'Treatment Protocols', icon: FileText, description: 'Clinical guidelines and treatment pathways learned over time.' },
    { name: 'knowledge_labs', label: 'Lab Reference', icon: BrainCircuit, description: 'Clinical significance and analysis of laboratory tests.' },
    { name: 'drugs', label: 'Drug Summaries', icon: Pill, description: 'Cached side effects, contraindications, and drug interactions.' },
    { name: 'chat_messages', label: 'Chat History', icon: MessageSquare, description: 'Persistent history of AI consultations and clinical reasoning.' },
    { name: 'patient_notes', label: 'AI Insights', icon: BrainCircuit, description: 'Clinical insights saved from AI conversations to patient records.' },
  ];

  const fetchStats = async () => {
    setLoading(true);
    try {
      const newStats = await Promise.all(learnedTables.map(async (table) => {
        // @ts-ignore
        const count = await db[table.name].count();
        return {
          ...table,
          count,
          tableName: table.name
        };
      }));
      setStats(newStats);
    } catch (error) {
      console.error("Error fetching database stats:", error);
      toast.error("Failed to load database statistics");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchStats();
  }, []);

  const handleClearTable = async (tableName: string, label: string) => {
    if (!window.confirm(`Are you sure you want to clear all data from ${label}? This action cannot be undone.`)) {
      return;
    }

    setClearing(tableName);
    try {
      // @ts-ignore
      await db[tableName].clear();
      toast.success(`${label} cleared successfully`);
      await fetchStats();
    } catch (error) {
      console.error(`Error clearing ${tableName}:`, error);
      toast.error(`Failed to clear ${label}`);
    } finally {
      setClearing(null);
    }
  };

  const handleExportData = async () => {
    try {
      const exportData: any = {};
      for (const table of learnedTables) {
        // @ts-ignore
        exportData[table.name] = await db[table.name].toArray();
      }
      
      const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `medical_ai_knowledge_${new Date().toISOString().split('T')[0]}.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      toast.success("Knowledge database exported successfully");
    } catch (error) {
      console.error("Export error:", error);
      toast.error("Failed to export database");
    }
  };

  return (
    <div className="max-w-5xl mx-auto space-y-8">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white">Database Manager</h2>
          <p className="text-slate-500 dark:text-slate-400 mt-1">Manage the clinical knowledge and insights learned by the AI system.</p>
        </div>
        <div className="flex gap-3">
          <button 
            onClick={fetchStats}
            className="p-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-700 transition-all"
            title="Refresh Statistics"
          >
            <RefreshCw className={cn("w-5 h-5", loading && "animate-spin")} />
          </button>
          <button 
            onClick={handleExportData}
            className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg font-bold hover:bg-indigo-700 transition-all shadow-sm"
          >
            <Download className="w-4 h-4" />
            Export Knowledge
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {stats.map((table) => (
          <motion.div 
            key={table.name}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 shadow-sm hover:shadow-md transition-all group"
          >
            <div className="flex items-start justify-between mb-4">
              <div className={cn(
                "p-3 rounded-xl",
                table.count > 0 ? "bg-indigo-50 dark:bg-indigo-500/10 text-indigo-600 dark:text-indigo-400" : "bg-slate-50 dark:bg-slate-800 text-slate-400"
              )}>
                <table.icon className="w-6 h-6" />
              </div>
              <div className="text-right">
                <div className="text-2xl font-black text-slate-900 dark:text-white">{table.count}</div>
                <div className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Records</div>
              </div>
            </div>
            
            <h3 className="font-bold text-slate-900 dark:text-white mb-1">{table.label}</h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed mb-6 h-12 line-clamp-3">
              {table.description}
            </p>

            <div className="flex items-center justify-between pt-4 border-t border-slate-100 dark:border-slate-800">
              <span className={cn(
                "text-[10px] font-bold uppercase px-2 py-0.5 rounded-full",
                table.count > 0 ? "bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400" : "bg-slate-100 dark:bg-slate-800 text-slate-400"
              )}>
                {table.count > 0 ? 'Active' : 'Empty'}
              </span>
              <button 
                onClick={() => handleClearTable(table.tableName, table.label)}
                disabled={table.count === 0 || clearing === table.tableName}
                className="p-2 text-slate-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-500/10 rounded-lg transition-all disabled:opacity-0"
                title={`Clear ${table.label}`}
              >
                {clearing === table.tableName ? (
                  <RefreshCw className="w-4 h-4 animate-spin" />
                ) : (
                  <Trash2 className="w-4 h-4" />
                )}
              </button>
            </div>
          </motion.div>
        ))}
      </div>

      <div className="bg-amber-50 dark:bg-amber-500/5 border border-amber-200 dark:border-amber-500/20 rounded-2xl p-6">
        <div className="flex items-start gap-4">
          <div className="p-2 bg-amber-100 dark:bg-amber-500/20 rounded-lg text-amber-600 dark:text-amber-400">
            <AlertCircle className="w-5 h-5" />
          </div>
          <div>
            <h4 className="font-bold text-amber-900 dark:text-amber-400">About Learned Data</h4>
            <p className="text-sm text-amber-800 dark:text-amber-500/80 mt-1 leading-relaxed">
              This data is generated dynamically as you interact with the AI Assistant and Knowledge Base. 
              Clearing these tables will remove cached clinical information, meaning the AI will need to re-generate 
              content for those terms, which may increase latency and API usage.
            </p>
            <div className="mt-4 flex items-center gap-6">
              <div className="flex items-center gap-2">
                <CheckCircle className="w-4 h-4 text-emerald-500" />
                <span className="text-xs font-medium text-amber-800 dark:text-amber-500/80">Local-first storage</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle className="w-4 h-4 text-emerald-500" />
                <span className="text-xs font-medium text-amber-800 dark:text-amber-500/80">Privacy preserved</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle className="w-4 h-4 text-emerald-500" />
                <span className="text-xs font-medium text-amber-800 dark:text-amber-500/80">Exportable clinical insights</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
