import React, { useState, useEffect } from 'react';
import { 
  Database, Trash2, RefreshCw, Search, FileText, BrainCircuit, Pill, 
  MessageSquare, AlertCircle, CheckCircle, Download, Wifi, WifiOff,
  Sliders, History, Play, ShieldAlert, Table, Settings, Clock, Server, Eye, ArrowRight
} from 'lucide-react';
import { db } from '../../lib/db';
import { cn } from '../../lib/utils';
import { toast } from 'sonner';
import { motion, AnimatePresence } from 'motion/react';
import { syncAll, restartSyncEngine, type SyncHistoryEntry } from '../../lib/sync';
import { supabase, supabaseEnabled } from '../../lib/supabase';

interface TableStats {
  name: string;
  count: number;
  label: string;
  icon: any;
  description: string;
  tableName: string;
}

export function DatabaseManagerSettings() {
  const [activeTab, setActiveTab] = useState<'sync' | 'knowledge'>('sync');
  const [stats, setStats] = useState<TableStats[]>([]);
  const [loading, setLoading] = useState(true);
  const [clearing, setClearing] = useState<string | null>(null);
  
  // Settings values
  const [syncBgEnabled, setSyncBgEnabled] = useState(() => localStorage.getItem('sync_background_enabled') !== 'false');
  const [syncInterval, setSyncInterval] = useState(() => Number(localStorage.getItem('sync_interval')) || 30000);
  const [conflictPolicy, setConflictPolicy] = useState(() => localStorage.getItem('sync_conflict_policy') || 'latest');
  
  // Realtime Connection Health
  const [localOnline, setLocalOnline] = useState(navigator.onLine);
  const [supabaseReachable, setSupabaseReachable] = useState<'checking' | 'yes' | 'no' | 'disabled'>('checking');
  const [pingLatency, setPingLatency] = useState<number | null>(null);

  // Sync Log lists
  const [pendingEvents, setPendingEvents] = useState<any[]>([]);
  const [syncHistory, setSyncHistory] = useState<SyncHistoryEntry[]>([]);
  const [isCurrentlySyncing, setIsCurrentlySyncing] = useState(false);
  
  // Active modal/inspector for details
  const [selectedEventPayload, setSelectedEventPayload] = useState<any | null>(null);

  const learnedTables = [
    { name: 'knowledge_encyclopedia', label: 'Medical Encyclopedia', icon: Search, description: 'Cached definitions and medical terms generated by AI.' },
    { name: 'knowledge_protocols', label: 'Treatment Protocols', icon: FileText, description: 'Clinical guidelines and treatment pathways learned over time.' },
    { name: 'knowledge_labs', label: 'Lab Reference', icon: BrainCircuit, description: 'Clinical significance and analysis of laboratory tests.' },
    { name: 'drugs', label: 'Drug Summaries', icon: Pill, description: 'Cached side effects, contraindications, and drug interactions.' },
    { name: 'chat_messages', label: 'Chat History', icon: MessageSquare, description: 'Persistent history of AI consultations and clinical reasoning.' },
    { name: 'patient_notes', label: 'AI Insights', icon: BrainCircuit, description: 'Clinical insights saved from AI conversations to patient records.' },
  ];

  const fetchStats = async () => {
    setLoading(true);
    try {
      const newStats = await Promise.all(learnedTables.map(async (table) => {
        // @ts-ignore
        const count = await db[table.name].count();
        return {
          ...table,
          count,
          tableName: table.name
        };
      }));
      setStats(newStats);
    } catch (error) {
      console.error("Error fetching database stats:", error);
      toast.error("Failed to load database statistics");
    } finally {
      setLoading(false);
    }
  };

  const checkSupabaseHealth = async () => {
    if (!supabaseEnabled) {
      setSupabaseReachable('disabled');
      return;
    }
    setSupabaseReachable('checking');
    try {
      const t0 = performance.now();
      const { error } = await supabase.from('patients').select('id').limit(1);
      if (error) throw error;
      const t1 = performance.now();
      setPingLatency(Math.round(t1 - t0));
      setSupabaseReachable('yes');
    } catch (err) {
      console.error("Supabase API connection failed:", err);
      setSupabaseReachable('no');
    }
  };

  const loadSyncCenterData = async () => {
    try {
      const events = await db.sync_events.toArray();
      setPendingEvents(events);
      
      const logsHistory = localStorage.getItem('sync_history') || '[]';
      setSyncHistory(JSON.parse(logsHistory));
    } catch (err) {
      console.error("Error loading sync center logs:", err);
    }
  };

  useEffect(() => {
    fetchStats();
    checkSupabaseHealth();
    loadSyncCenterData();

    const handleSyncStateChanged = (e: Event) => {
      const customEvent = e as CustomEvent;
      if (customEvent.detail) {
        setIsCurrentlySyncing(customEvent.detail.isSyncing);
      }
      loadSyncCenterData();
    };

    const handleHistoryUpdated = () => {
      loadSyncCenterData();
    };

    const handleOnlineStatusChange = () => {
      setLocalOnline(navigator.onLine);
      checkSupabaseHealth();
    };

    window.addEventListener('sync_state_changed', handleSyncStateChanged);
    window.addEventListener('sync_history_updated', handleHistoryUpdated);
    window.addEventListener('online', handleOnlineStatusChange);
    window.addEventListener('offline', handleOnlineStatusChange);

    return () => {
      window.removeEventListener('sync_state_changed', handleSyncStateChanged);
      window.removeEventListener('sync_history_updated', handleHistoryUpdated);
      window.removeEventListener('online', handleOnlineStatusChange);
      window.removeEventListener('offline', handleOnlineStatusChange);
    };
  }, []);

  const handleClearTable = async (tableName: string, label: string) => {
    if (!window.confirm(`Are you sure you want to clear all data from ${label}? This action cannot be undone.`)) {
      return;
    }

    setClearing(tableName);
    try {
      // @ts-ignore
      await db[tableName].clear();
      toast.success(`${label} cleared successfully`);
      await fetchStats();
    } catch (error) {
      console.error(`Error clearing ${tableName}:`, error);
      toast.error(`Failed to clear ${label}`);
    } finally {
      setClearing(null);
    }
  };

  const handleExportData = async () => {
    try {
      const exportData: any = {};
      for (const table of learnedTables) {
        // @ts-ignore
        exportData[table.name] = await db[table.name].toArray();
      }
      
      const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `medical_ai_knowledge_${new Date().toISOString().split('T')[0]}.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      toast.success("Knowledge database exported successfully");
    } catch (error) {
      console.error("Export error:", error);
      toast.error("Failed to export database");
    }
  };

  const handleManualSyncNow = async () => {
    if (isCurrentlySyncing) return;
    toast.info("Database synchronization started...");
    const result = await syncAll('manual');
    if (result) {
      if (result.status === 'success') {
        const totalPushed = result.pushedCount;
        const totalPulled = Object.values(result.pulledCounts).reduce((a, b) => a + b, 0);
        toast.success(`Sync completed in ${result.durationMs}ms. Sent ${totalPushed} changes; retrieved ${totalPulled} updates.`);
      } else if (result.status === 'network_offline') {
        toast.warning("Sync bypassed. You are currently offline.");
      } else {
        toast.error(`Sync reported issues: ${result.message || 'Unknown network error'}`);
      }
    }
  };

  const handleToggleBgSync = (enabled: boolean) => {
    setSyncBgEnabled(enabled);
    localStorage.setItem('sync_background_enabled', String(enabled));
    restartSyncEngine();
    toast.success(enabled ? "Automatic background synchronization enabled." : "Background sync paused. Local changes will accumulate offline.");
  };

  const handleSyncIntervalChange = (val: number) => {
    setSyncInterval(val);
    localStorage.setItem('sync_interval', String(val));
    restartSyncEngine();
    toast.success(`Sync interval adjusted to ${val / 1000} seconds.`);
  };

  const handleConflictPolicyChange = (policy: string) => {
    setConflictPolicy(policy);
    localStorage.setItem('sync_conflict_policy', policy);
    toast.success(`Conflict resolution set to: ${
      policy === 'latest' ? 'Latest Modifier Wins' : policy === 'server' ? 'Server/Cloud Wins' : 'Client Wins'
    }`);
  };

  const handlePurgeQueue = async () => {
    if (!window.confirm("Purging this transaction queue will remove outstanding clinical modifications without pushing them to the shared server. Use only for troubleshooting. Proceed?")) {
      return;
    }
    try {
      await db.sync_events.clear();
      toast.success("Sync queue purged successfully.");
      loadSyncCenterData();
    } catch (err) {
      toast.error("Failed to empty transaction queue.");
    }
  };

  return (
    <div className="max-w-5xl mx-auto space-y-8">
      {/* Header section with tabs selector styling */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white">Clinical DB & Sync Manager</h2>
          <p className="text-slate-500 dark:text-slate-400 mt-1">Configure offline-first parameters, resolve merge conflicts and administer local AI knowledge files.</p>
        </div>
        
        {/* Modern high-contrast Tab Buttons */}
        <div className="flex bg-slate-100 dark:bg-slate-800 p-1 rounded-xl self-start border border-slate-200 dark:border-slate-700">
          <button
            onClick={() => setActiveTab('sync')}
            className={cn(
              "flex items-center gap-2 px-4 py-1.5 rounded-lg text-xs font-bold transition-all",
              activeTab === 'sync' 
                ? "bg-white dark:bg-slate-900 text-indigo-600 dark:text-indigo-450 shadow-sm"
                : "text-slate-600 dark:text-slate-400 hover:text-slate-900"
            )}
          >
            <RefreshCw className={cn("w-3.5 h-3.5", isCurrentlySyncing && "animate-spin")} />
            Sync & Offline Console
          </button>
          <button
            onClick={() => setActiveTab('knowledge')}
            className={cn(
              "flex items-center gap-2 px-4 py-1.5 rounded-lg text-xs font-bold transition-all",
              activeTab === 'knowledge' 
                ? "bg-white dark:bg-slate-900 text-indigo-600 dark:text-indigo-450 shadow-sm"
                : "text-slate-600 dark:text-slate-400 hover:text-slate-900"
            )}
          >
            <BrainCircuit className="w-3.5 h-3.5" />
            Knowledge Base Stats
          </button>
        </div>
      </div>

      {activeTab === 'sync' ? (
        <div className="space-y-8">
          {/* Health connection widget */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className={cn(
                  "p-3 rounded-xl",
                  localOnline ? "bg-emerald-50 dark:bg-emerald-500/15 text-emerald-600 dark:text-emerald-400" : "bg-rose-50 dark:bg-rose-500/15 text-rose-600 dark:text-rose-400"
                )}>
                  {localOnline ? <Wifi className="w-5 h-5" /> : <WifiOff className="w-5 h-5" />}
                </div>
                <div>
                  <div className="text-xs text-slate-400 font-medium">Browser Connection</div>
                  <div className="text-sm font-bold text-slate-900 dark:text-white">
                    {localOnline ? 'Connected (Online)' : 'Stand-alone / Offline'}
                  </div>
                </div>
              </div>
              <span className="flex h-2.5 w-2.5 relative">
                <span className={cn(
                  "animate-ping absolute inline-flex h-full w-full rounded-full opacity-75",
                  localOnline ? "bg-emerald-400" : "bg-rose-400"
                )}></span>
                <span className={cn("relative inline-flex rounded-full h-2.5 w-2.5", localOnline ? "bg-emerald-500" : "bg-rose-500")}></span>
              </span>
            </div>

            <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className={cn(
                  "p-3 rounded-xl",
                  supabaseReachable === 'checking' ? "bg-slate-50 dark:bg-slate-800 text-slate-400 animate-pulse" :
                  supabaseReachable === 'yes' ? "bg-emerald-50 dark:bg-emerald-500/15 text-emerald-600 dark:text-emerald-400" :
                  supabaseReachable === 'disabled' ? "bg-amber-50 dark:bg-amber-500/15 text-amber-600 dark:text-amber-400" :
                  "bg-rose-50 dark:bg-rose-500/15 text-rose-600 dark:text-rose-400"
                )}>
                  {supabaseReachable === 'yes' ? <Server className="w-5 h-5" /> : <Server className="w-5 h-5 opacity-60" />}
                </div>
                <div>
                  <div className="text-xs text-slate-400 font-medium">Supabase Reachability</div>
                  <div className="text-sm font-bold text-slate-900 dark:text-white">
                    {supabaseReachable === 'checking' ? 'Testing Api...' :
                     supabaseReachable === 'yes' ? `Active (${pingLatency}ms)` :
                     supabaseReachable === 'disabled' ? 'Missing Credentials' :
                     'Unreachable / Offline'}
                  </div>
                </div>
              </div>
              <button 
                onClick={checkSupabaseHealth}
                className="p-1.5 text-slate-400 hover:text-indigo-600 hover:bg-slate-50 dark:hover:bg-slate-800 rounded-lg transition-all"
                title="Verify connection"
              >
                <RefreshCw className={cn("w-4 h-4", supabaseReachable === 'checking' && "animate-spin")} />
              </button>
            </div>

            <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="p-3 bg-indigo-50 dark:bg-indigo-500/15 text-indigo-600 dark:text-indigo-400 rounded-xl">
                  <Clock className="w-5 h-5" />
                </div>
                <div>
                  <div className="text-xs text-slate-400 font-medium">Last Successful Sync</div>
                  <div className="text-sm font-bold text-slate-900 dark:text-white">
                    {localStorage.getItem('last_sync_time') 
                      ? new Date(localStorage.getItem('last_sync_time')!).toLocaleTimeString() 
                      : 'Never synchronized'}
                  </div>
                </div>
              </div>
              <button 
                onClick={handleManualSyncNow}
                disabled={isCurrentlySyncing}
                className="px-3 py-1 bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white rounded-lg text-xs font-bold transition-all shadow-sm flex items-center gap-1"
              >
                <Play className="w-3 h-3" /> Sync Now
              </button>
            </div>
          </div>

          {/* Sync Engine Setup Controls */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 shadow-sm">
              <div className="flex items-center gap-2 mb-6">
                <Sliders className="w-4 h-4 text-indigo-500" />
                <h3 className="font-bold text-slate-900 dark:text-white">Delta Sync Policy Configuration</h3>
              </div>
              
              <div className="space-y-6">
                {/* Background Sync Toggle */}
                <div className="flex items-center justify-between pb-4 border-b border-slate-100 dark:border-slate-800">
                  <div>
                    <div className="text-sm font-bold text-slate-900 dark:text-white">Automatic Background Sync</div>
                    <div className="text-xs text-slate-500">Periodically upload changes and fetch remote logs automatically.</div>
                  </div>
                  <label className="relative inline-flex items-center cursor-pointer select-none">
                    <input 
                      type="checkbox" 
                      className="sr-only peer"
                      checked={syncBgEnabled}
                      onChange={(e) => handleToggleBgSync(e.target.checked)}
                    />
                    <div className="w-9 h-5 bg-slate-200 dark:bg-slate-800 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-slate-300 after:border after:rounded-full after:height-4 after:w-4 after:transition-all dark:border-slate-600 peer-checked:bg-indigo-600"></div>
                  </label>
                </div>

                {/* Interval selection */}
                <div className="flex items-center justify-between pb-4 border-b border-slate-100 dark:border-slate-800">
                  <div>
                    <div className="text-sm font-bold text-slate-900 dark:text-white">Sync Frequency Interval</div>
                    <div className="text-xs text-slate-500">Frequency of background cycles when online.</div>
                  </div>
                  <select 
                    value={syncInterval}
                    onChange={(e) => handleSyncIntervalChange(Number(e.target.value))}
                    disabled={!syncBgEnabled}
                    className="bg-slate-50 dark:bg-slate-850 p-1.5 border border-slate-200 dark:border-slate-750 text-xs font-bold rounded-lg text-slate-800 dark:text-white"
                  >
                    <option value={10000}>Every 10 seconds</option>
                    <option value={30000}>Every 30 seconds</option>
                    <option value={60000}>Every 1 minute</option>
                    <option value={300000}>Every 5 minutes</option>
                  </select>
                </div>

                {/* Conflict resolution selectors */}
                <div>
                  <div className="text-sm font-bold text-slate-900 dark:text-white mb-2">Conflict Resolution Rules Mode</div>
                  <div className="text-xs text-slate-500 mb-4">Select system behavior when a record differs locally and in the shared cloud.</div>
                  
                  <div className="grid grid-cols-3 gap-3">
                    <button
                      onClick={() => handleConflictPolicyChange('latest')}
                      className={cn(
                        "p-3 rounded-xl border text-center transition-all",
                        conflictPolicy === 'latest'
                          ? "border-indigo-500 bg-indigo-50/10 text-indigo-700 dark:text-indigo-400 font-bold"
                          : "border-slate-200 dark:border-slate-800 hover:bg-slate-50"
                      )}
                    >
                      <Clock className="w-4 h-4 mx-auto mb-1 opacity-70" />
                      <div className="text-[10px] uppercase font-bold tracking-wider">Latest Wins</div>
                      <div className="text-[8px] text-slate-400 mt-1">Based on timestamp</div>
                    </button>
                    
                    <button
                      onClick={() => handleConflictPolicyChange('server')}
                      className={cn(
                        "p-3 rounded-xl border text-center transition-all",
                        conflictPolicy === 'server'
                          ? "border-indigo-500 bg-indigo-50/10 text-indigo-700 dark:text-indigo-400 font-bold"
                          : "border-slate-200 dark:border-slate-800 hover:bg-slate-50"
                      )}
                    >
                      <Server className="w-4 h-4 mx-auto mb-1 opacity-70" />
                      <div className="text-[10px] uppercase font-bold tracking-wider">Cloud Wins</div>
                      <div className="text-[8px] text-slate-400 mt-1">Overwrite locally</div>
                    </button>

                    <button
                      onClick={() => handleConflictPolicyChange('client')}
                      className={cn(
                        "p-3 rounded-xl border text-center transition-all",
                        conflictPolicy === 'client'
                          ? "border-indigo-500 bg-indigo-50/10 text-indigo-700 dark:text-indigo-400 font-bold"
                          : "border-slate-200 dark:border-slate-800 hover:bg-slate-50"
                      )}
                    >
                      <Eye className="w-4 h-4 mx-auto mb-1 opacity-70" />
                      <div className="text-[10px] uppercase font-bold tracking-wider">Client Wins</div>
                      <div className="text-[8px] text-slate-400 mt-1">Preserve local edit</div>
                    </button>
                  </div>
                </div>
              </div>
            </div>

            {/* Dirty local transaction queue */}
            <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 shadow-sm overflow-hidden flex flex-col justify-between">
              <div>
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
                    <Table className="w-4 h-4 text-amber-500" />
                    <h3 className="font-bold text-slate-900 dark:text-white">Unsynced Local Queue</h3>
                  </div>
                  <span className={cn(
                    "text-xs px-2.5 py-1 rounded-full font-bold",
                    pendingEvents.length > 0 ? "bg-amber-100 text-amber-800" : "bg-emerald-100 text-emerald-800"
                  )}>
                    {pendingEvents.length} Pending Actions
                  </span>
                </div>
                <p className="text-xs text-slate-500 mb-4 h-8">
                  These modifications are saved securely on this offline browser. They will push to Supabase once connection recovers.
                </p>

                {pendingEvents.length > 0 ? (
                  <div className="space-y-2 max-h-[170px] overflow-y-auto pr-1">
                    {pendingEvents.slice(0, 5).map((e, index) => (
                      <div key={e.id || index} className="flex items-center justify-between bg-slate-50 dark:bg-slate-850 p-2.5 rounded-xl border border-slate-100 dark:border-slate-800 text-xs">
                        <div className="flex items-center gap-2">
                          <span className={cn(
                            "px-1.5 py-0.5 rounded text-[9px] font-extrabold uppercase",
                            e.action === 'CREATE' ? "bg-emerald-100 text-emerald-800" :
                            e.action === 'UPDATE' ? "bg-indigo-100 text-indigo-800" :
                            "bg-rose-100 text-rose-800"
                          )}>
                            {e.action}
                          </span>
                          <div>
                            <span className="font-bold capitalize text-slate-850 dark:text-white">{e.entityType.replace('_', ' ')}</span>
                            <span className="text-slate-400 text-[10px] ml-1.5">ID: {e.entityId.slice(0, 8)}</span>
                          </div>
                        </div>
                        <div className="flex items-center gap-2 text-slate-405">
                          <span>{new Date(e.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>
                          <button 
                            onClick={() => setSelectedEventPayload(e)}
                            className="p-1 text-slate-400 hover:text-indigo-600 rounded-md hover:bg-white"
                            title="Inspect Data Content"
                          >
                            <Eye className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      </div>
                    ))}
                    {pendingEvents.length > 5 && (
                      <div className="text-center text-[10px] text-slate-400 italic pt-1">
                        ... and {pendingEvents.length - 5} other transactions waiting
                      </div>
                    )}
                  </div>
                ) : (
                  <div className="flex flex-col items-center justify-center p-8 border border-dashed border-slate-200 dark:border-slate-800 rounded-2xl h-[170px]">
                    <CheckCircle className="w-8 h-8 text-emerald-400 mb-2" />
                    <div className="text-xs font-bold text-slate-650">Local state fully synchronized</div>
                    <div className="text-[10px] text-slate-400">0 modifications waiting in delta outbox.</div>
                  </div>
                )}
              </div>

              {pendingEvents.length > 0 && (
                <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-100 dark:border-slate-850 mt-4">
                  <button 
                    onClick={handlePurgeQueue}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-rose-50 hover:bg-rose-100 text-rose-600 rounded-lg text-xs font-bold transition-all"
                  >
                    <Trash2 className="w-3.5 h-3.5" /> Discard Outbox
                  </button>
                  <button 
                    onClick={handleManualSyncNow}
                    disabled={isCurrentlySyncing}
                    className="flex items-center gap-1.5 px-4 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-xs font-bold transition-all shadow-sm"
                  >
                    <Play className="w-3.5 h-3.5" /> Push Transactions
                  </button>
                </div>
              )}
            </div>
          </div>

          {/* Sync history logbook */}
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 shadow-sm">
            <div className="flex items-center justify-between mb-6 border-b border-slate-100 dark:border-slate-800 pb-4">
              <div className="flex items-center gap-2">
                <History className="w-4 h-4 text-indigo-500" />
                <div>
                  <h3 className="font-bold text-slate-900 dark:text-white">Synchronization Activity Logbook</h3>
                  <p className="text-xs text-slate-500">History of the latest background and manual sync actions.</p>
                </div>
              </div>
              <button 
                onClick={() => {
                  localStorage.setItem('sync_history', '[]');
                  loadSyncCenterData();
                  toast.success("Activity log cleared.");
                }}
                className="text-xs font-bold text-slate-400 hover:text-red-500 flex items-center gap-1 transition-all"
              >
                <Trash2 className="w-3.5 h-3.5" /> Empty Logbook
              </button>
            </div>

            {syncHistory.length > 0 ? (
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs text-slate-600 dark:text-slate-400 border-collapse">
                  <thead>
                    <tr className="border-b border-slate-100 dark:border-slate-800 text-slate-450 uppercase tracking-wider text-[9px] font-bold">
                      <th className="pb-3 text-slate-500">Timestamp</th>
                      <th className="pb-3 text-slate-500">Trigger</th>
                      <th className="pb-3 text-slate-500">Status</th>
                      <th className="pb-3 text-slate-500">Payload Transferred</th>
                      <th className="pb-3 text-slate-500">Elapsed Time</th>
                      <th className="pb-3 text-slate-500">Details</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                    {syncHistory.map((item, index) => {
                      const totalPulled = Object.values(item.pulledCounts || {}).reduce((a, b) => a + b, 0);
                      return (
                        <tr key={item.timestamp || index} className="hover:bg-slate-50/50 dark:hover:bg-slate-800/10">
                          <td className="py-3.5">
                            <span className="text-slate-900 dark:text-white font-medium">{new Date(item.timestamp).toLocaleDateString()}</span>
                            <span className="text-slate-400 ml-1.5 font-mono">{new Date(item.timestamp).toLocaleTimeString([], { hour12: false })}</span>
                          </td>
                          <td className="py-3.5">
                            <span className={cn(
                              "text-[10px] px-2 py-0.5 rounded-full font-bold capitalize",
                              item.type === 'manual' ? "bg-amber-50 dark:bg-amber-500/10 text-amber-600" : "bg-slate-100 dark:bg-slate-800 text-slate-500"
                            )}>
                              {item.type}
                            </span>
                          </td>
                          <td className="py-3.5">
                            {item.status === 'success' ? (
                              <span className="text-emerald-500 font-bold flex items-center gap-1">
                                <CheckCircle className="w-3.5 h-3.5" /> Complete
                              </span>
                            ) : item.status === 'network_offline' ? (
                              <span className="text-rose-500 font-bold flex items-center gap-1">
                                <WifiOff className="w-3.5 h-3.5" /> Offline Offline
                              </span>
                            ) : (
                              <span className="text-amber-500 font-bold flex items-center gap-1" title={item.message}>
                                <ShieldAlert className="w-3.5 h-3.5" /> Failed
                              </span>
                            )}
                          </td>
                          <td className="py-3.5">
                            {item.status === 'success' ? (
                              <div className="flex flex-wrap gap-1 item-center">
                                {item.pushedCount > 0 && (
                                  <span className="bg-indigo-50 dark:bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 text-[10px] px-1.5 py-0.5 rounded font-medium">
                                    ↑ {item.pushedCount} Pushed
                                  </span>
                                )}
                                {totalPulled > 0 ? (
                                  <span className="bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 text-[10px] px-1.5 py-0.5 rounded font-medium" title={JSON.stringify(item.pulledCounts)}>
                                    ↓ {totalPulled} Pulled
                                  </span>
                                ) : (
                                  item.pushedCount === 0 && <span className="text-slate-400 text-[10px]">No modified entries</span>
                                )}
                              </div>
                            ) : (
                              <span className="text-rose-400 italic max-w-xs truncate block" title={item.message}>
                                {item.message || 'Error executing syncing'}
                              </span>
                            )}
                          </td>
                          <td className="py-3.5 font-mono opacity-80">{item.durationMs || 0} ms</td>
                          <td className="py-3.5">
                            {item.status === 'failed' && (
                              <button
                                onClick={() => setSelectedEventPayload({ error: item.message, timestamp: item.timestamp })}
                                className="text-xs text-indigo-500 hover:underline font-bold"
                              >
                                View Error
                              </button>
                            )}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            ) : (
              <div className="text-center py-12 border border-dashed border-slate-200 dark:border-slate-800 rounded-2xl">
                <Clock className="w-8 h-8 text-slate-300 mx-auto mb-2" />
                <span className="text-xs font-bold text-slate-500">No sync attempts recorded</span>
                <p className="text-[10px] text-slate-400 max-w-xs mx-auto mt-0.5">Start a manual synchronization or trigger actions to build event rows.</p>
              </div>
            )}
          </div>
        </div>
      ) : (
        /* Original stats list section - modularized safely inside the right tab folder */
        <div className="space-y-8">
          <div className="flex items-center justify-between bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm">
            <div>
              <h3 className="font-bold text-slate-900 dark:text-white">Cached AI Clinical Intelligence</h3>
              <p className="text-xs text-slate-500 mt-0.5">Export or purge clinical records dynamically generated during diagnosis matching.</p>
            </div>
            <button 
              onClick={handleExportData}
              className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg font-bold text-xs hover:bg-indigo-700 transition-all shadow-sm"
            >
              <Download className="w-4 h-4" /> Export Knowledge
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {stats.map((table) => (
              <motion.div 
                key={table.name}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 shadow-sm hover:shadow-md transition-all group"
              >
                <div className="flex items-start justify-between mb-4">
                  <div className={cn(
                    "p-3 rounded-xl",
                    table.count > 0 ? "bg-indigo-50 dark:bg-indigo-500/10 text-indigo-600 dark:text-indigo-400" : "bg-slate-50 dark:bg-slate-800 text-slate-400"
                  )}>
                    <table.icon className="w-6 h-6" />
                  </div>
                  <div className="text-right">
                    <div className="text-2xl font-black text-slate-900 dark:text-white">{table.count}</div>
                    <div className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Records</div>
                  </div>
                </div>
                
                <h3 className="font-bold text-slate-900 dark:text-white mb-1">{table.label}</h3>
                <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed mb-6 h-12 line-clamp-3">
                  {table.description}
                </p>

                <div className="flex items-center justify-between pt-4 border-t border-slate-100 dark:border-slate-800">
                  <span className={cn(
                    "text-[10px] font-bold uppercase px-2 py-0.5 rounded-full",
                    table.count > 0 ? "bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400" : "bg-slate-100 dark:bg-slate-800 text-slate-400"
                  )}>
                    {table.count > 0 ? 'Active' : 'Empty'}
                  </span>
                  <button 
                    onClick={() => handleClearTable(table.tableName, table.label)}
                    disabled={table.count === 0 || clearing === table.tableName}
                    className="p-2 text-slate-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-500/10 rounded-lg transition-all disabled:opacity-0"
                    title={`Clear ${table.label}`}
                  >
                    {clearing === table.tableName ? (
                      <RefreshCw className="w-4 h-4 animate-spin" />
                    ) : (
                      <Trash2 className="w-4 h-4" />
                    )}
                  </button>
                </div>
              </motion.div>
            ))}
          </div>

          <div className="bg-amber-50 dark:bg-amber-500/5 border border-amber-200 dark:border-amber-500/20 rounded-2xl p-6">
            <div className="flex items-start gap-4">
              <div className="p-2 bg-amber-100 dark:bg-amber-500/20 rounded-lg text-amber-600 dark:text-amber-400">
                <AlertCircle className="w-5 h-5" />
              </div>
              <div>
                <h4 className="font-bold text-amber-900 dark:text-amber-400">About Learned Data</h4>
                <p className="text-sm text-amber-800 dark:text-amber-500/80 mt-1 leading-relaxed">
                  This data is generated dynamically as you interact with the AI Assistant and Knowledge Base. 
                  Clearing these tables will remove cached clinical information, meaning the AI will need to re-generate 
                  content for those terms, which may increase latency and API usage.
                </p>
                <div className="mt-4 flex flex-wrap gap-x-6 gap-y-2">
                  <div className="flex items-center gap-2">
                    <CheckCircle className="w-4 h-4 text-emerald-500" />
                    <span className="text-xs font-medium text-amber-800 dark:text-amber-500/80">Local-first storage</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle className="w-4 h-4 text-emerald-500" />
                    <span className="text-xs font-medium text-amber-800 dark:text-amber-500/80">Privacy preserved</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle className="w-4 h-4 text-emerald-500" />
                    <span className="text-xs font-medium text-amber-800 dark:text-amber-500/80">Exportable clinical insights</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Expandable Dialog Payload Overlay Drawer */}
      <AnimatePresence>
        {selectedEventPayload && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 backdrop-blur-xs p-4">
            <motion.div 
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-2xl max-w-2xl w-full max-h-[80vh] flex flex-col justify-between"
            >
              <div>
                <div className="flex items-center justify-between mb-4 border-b border-slate-100 dark:border-slate-850 pb-3">
                  <h4 className="font-bold text-slate-900 dark:text-white flex items-center gap-2">
                    <Eye className="w-4 h-4 text-indigo-500" />
                    {selectedEventPayload.action ? "Inspect Pending Transaction Payload" : "Sync Error Log Inspector"}
                  </h4>
                  <button 
                    onClick={() => setSelectedEventPayload(null)}
                    className="p-1 px-2 hover:bg-slate-100 dark:hover:bg-slate-850 rounded-lg text-slate-500 text-xs font-bold transition-all"
                  >
                    Close
                  </button>
                </div>
                
                {selectedEventPayload.action && (
                  <div className="grid grid-cols-2 gap-4 bg-slate-50 dark:bg-slate-850 p-3 rounded-2xl mb-4 text-xs font-bold font-mono">
                    <div>Entity: <span className="text-slate-500">{selectedEventPayload.entityType}</span></div>
                    <div>Event UUID: <span className="text-slate-500">{selectedEventPayload.eventId.slice(0, 12)}</span></div>
                    <div>Action type: <span className="text-emerald-600">{selectedEventPayload.action}</span></div>
                    <div>Time modified: <span className="text-slate-500">{new Date(selectedEventPayload.timestamp).toLocaleString()}</span></div>
                  </div>
                )}

                <div className="bg-slate-900 dark:bg-black rounded-2xl p-4 overflow-y-auto max-h-[40vh] text-left">
                  <pre className="text-[11px] font-mono text-emerald-400 whitespace-pre-wrap">
                    {JSON.stringify(selectedEventPayload.payload || selectedEventPayload, null, 2)}
                  </pre>
                </div>
              </div>

              <div className="flex items-center justify-end pt-4 border-t border-slate-150 dark:border-slate-850 mt-4">
                <button 
                  onClick={() => setSelectedEventPayload(null)}
                  className="px-5 py-2 bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-350 font-bold rounded-xl text-xs hover:bg-slate-200 transition-all"
                >
                  Close
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
